### ISSUE TITLE
Some sites with this theme have redirect errors

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-news-hub-theme#11]
Some sites with this theme have redirect or 500 errors, see:
http://thinkingmatters.uncc.edu/
https://clas-pages.uncc.edu/japan/

This errors appeared when the theme was updated in prod.  Same updates in dev do not have same issues, see:
https://clas-incubator-wp.uncc.edu/exchange02/

**Comment by marpa** [comment]
This was resolved by getting a copy of dev version of theme and uploading to prod.  It must be that the dev version had changes that had NOT been committed to this repo...

**Comment by atrus1701** [comment]
The most recent version was already submitted to git and on clas-incubator-wp, so it seems strange that this happened.  I'll look into it when I can.

**Comment by marpa** [comment]
This has been resolved
