### ISSUE TITLE
Custom code needs to be added for form data

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-news-hub-theme#19]
Custom code needs to be added for form data.  In particular, need to concatenate date and time info into a single field that the Formidable plugin can use to generate event posts

Original theme added this code to the theme's functions.php.  Better to implement as a separate plugin...

**Comment by clas-web** [comment]
A separate plugin called Exchange Online Event Form Fix has been created for this, see:
https://github.com/clas-web/exchange-online-event-form-fix.git
