### ISSUE TITLE
In the news listing page number of items

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-news-hub-theme#21]
The In-the-news listing page should have 20 items, but only has 10.  Compare:
- https://devexchange.uncc.edu/in-the-news/
- https://exchange.uncc.edu/in-the-news/

**Comment by atrus1701** [comment]
Just need to update the Archive posts number in the "Edit Section" of the "In the News" section.  I updated it on devexchange, but will need to be updated when production is updated to the new theme.
