### ISSUE TITLE
Add thumbnail images to description field of student stories RSS feed

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-news-hub-theme#27]
Add thumbnail images to description field of student stories RSS feed. Will require modifying the code used to add images to the selected student stories RSS feed.

To do this modify the functions.php:
`if( $category->slug == 'news' || $category->slug == 'research' || 'student-stories')`

**Comment by amarciniak25** [comment]
the code has been updated

**Comment by clas-web** [comment]
commit: 532a4f688d89658a6a2be3d972f1303dcb42fcb3
